spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          min-partition-count: 3
      bindings:
        greetings-out:
          destination: greetings
          contentType: application/json
